services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - dados_do_banco:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  dados_do_banco:
